
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package uk.co.certait.ws.service;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2014-02-24T11:40:25.767Z
 * Generated source version: 2.7.7
 * 
 */
public class CustomerServiceClient {

    public static void main(String[] args) throws Exception {
        QName serviceName = new QName("http://certait.co.uk", "CustomerServiceService");
        QName portName = new QName("http://certait.co.uk", "CustomerServicePort");

        Service service = Service.create(serviceName);
        service.addPort(portName, SOAPBinding.SOAP11HTTP_BINDING,
                        "http://localhost:9090/CustomerServicePort"); 
        uk.co.certait.ws.service.CustomerService client = service.getPort(portName,  uk.co.certait.ws.service.CustomerService.class);
        
        // Insert code to invoke methods on the client here
    }

}