
package uk.co.certait.ws.service;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2014-02-23T16:35:40.132Z
 * Generated source version: 2.7.7
 * 
 */
 
public class CustomerServiceServer{

    protected CustomerServiceServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new uk.co.certait.ws.service.CustomerServiceImpl();
        String address = "http://localhost:9090/CustomerServicePort";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new CustomerServiceServer();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
 
 