
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package uk.co.certait.ws.service;
import javax.jws.WebService;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2014-02-24T11:40:25.694Z
 * Generated source version: 2.7.7
 * 
 */
@WebService(endpointInterface = "uk.co.certait.ws.service.CustomerService", serviceName = "CustomerServiceService")                      
public class CustomerServiceImpl implements CustomerService {

    public uk.co.certait.ws.domain.Customer getCustomer(long arg0) {  
        System.out.println(arg0);    
        try {
            uk.co.certait.ws.domain.Customer _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
 
    }

}